repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
    -   id: markdownlint
        args: ["--ignore", "node_modules"]

-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
    -   id: git-check
    -   id: script-must-have-extension
    -   id: script-must-not-have-extension 