name: "Auto Label"
on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Check for conventional title
        uses: amannn/action-semantic-pull-request@v5
        if: github.event_name == 'pull_request_target'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types:
            - feat
            - fix
            - docs
            - style
            - refactor
            - perf
            - test
            - build
            - ci
            - chore
            - revert
          requireScope: false
          wip: true

      # Label based on matched patterns in title and body
      - name: Label based on title and body
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true

      # Automatically label PRs based on file paths changes
      - name: Label based on changed files
        if: github.event_name == 'pull_request_target'
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/file-labeler.yml
          sync-labels: false

      # Automatically label issues based on content
      - name: Label issues based on content
        if: github.event_name == 'issues'
        uses: github/issue-labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
          include-title: 1

